export const LOAD_CAMPAIGNS_START = 'LOAD_CAMPAIGNS_START';
export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS';
export const LOAD_CAMPAIGNS_ERROR = 'LOAD_CAMPAIGNS_ERROR';

export const ON_FILTER = 'ON_FILTER';
export const UPDATE_DATE = 'UPDATE_DATE';